apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-tweetpolite

commonLabels:
  app.kubernetes.io/name: tweetpolite

secretGenerator:
  - name: twitter-auth
    files:
      - secrets/twitter-auth.json

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml